// Conseils d'exécution complémentaires (exercices sans conseil dans leur fiche), par nom exact.
window.CONSEILS = {
  'Planche (straddle)': 'Jambes écartées pour raccourcir le levier ; bras verrouillés, omoplates écartées et basses.',
  'Pompes planche (tuck planche push-up)': 'Garder les épaules devant les mains pendant toute la descente ; coudes près du corps.',
  'Front lever tuck': 'Genoux contre la poitrine, bras tendus, omoplates abaissées ; dos rond au départ, puis plat avec la progression.',
  'Front lever rows': 'Depuis le front lever (ou un tuck), tirer la barre vers le bas du sternum sans laisser tomber les hanches.',
  'Support sur barres (straight bar support)': 'Bras tendus, épaules loin des oreilles, corps légèrement creusé : base du muscle up.',
  'Négatives de muscle up': 'Partir en haut du dip et descendre lentement à travers la transition jusqu’en suspension.',
  'Transition muscle up au sol (bande)': 'Barre basse, pieds au sol ou élastique : apprendre à basculer les poignets par-dessus la barre.',
  'Tractions en pause (L, 90°, haut)': 'Marquer 2 à 3 s à chaque angle (bras tendus, coudes à 90°, menton au-dessus de la barre).',
  'Pompes Hindu / dive bomber': 'Partir en pike, plonger poitrine près du sol en arc, finir en cobra ; revenir en sens inverse.',
  'Handstand push-up libre': 'Descendre la tête entre les mains (triangle), corps gainé ; travailler d’abord contre le mur.',
  'Press to handstand': 'Hanches au-dessus des mains, épaules en avant, monter les jambes par la compression sans sauter.',
  'Tuck sit vers L-sit': 'Pousser fort dans les appuis, puis tendre une jambe, puis les deux.',
  'Manna (progressions)': 'Mains derrière les hanches, épaules en extension maximale, bassin poussé vers l’avant.',
  'Swing kettlebell un bras': 'Comme le swing classique, en résistant à la rotation du buste ; changer de main au point haut.',
  'Kettlebell clean': 'Garder la kettlebell près du corps, la recevoir en rack sans qu’elle frappe l’avant-bras.',
  'Kettlebell snatch': 'Extension de hanche explosive, coude qui suit, poignet qui « perce » la poignée en haut.',
  'Kettlebell press': 'Depuis le rack, avant-bras vertical, fessiers et abdos serrés ; verrouiller au-dessus de la tête.',
  'Kettlebell windmill': 'Bras chargé vertical, regarder la kettlebell, pousser la hanche du côté chargé vers l’extérieur.',
  'Squat kettlebell double (front rack)': 'Coudes serrés, buste droit, descendre entre les genoux.',
  'Tirage vertical bras tendus à genoux': 'À genoux face à la poulie haute, bras tendus, ramener la barre aux cuisses en abaissant les omoplates.',
  'Rowing poulie unilatéral': 'Laisser l’épaule avancer en étirement puis tirer le coude vers la hanche, sans tourner le buste.',
  'Rowing haut à la corde (vers le visage)': 'Tirer vers le nez, coudes hauts et ouverts, finir en rotation externe.',
  'Croix de fer à la poulie (Y)': 'Poulies basses croisées, monter les bras en Y, pouces vers le haut, épaules basses.',
  'Oiseau à la poulie': 'Câbles croisés à hauteur d’épaules, ouvrir les bras tendus vers l’arrière sans hausser les épaules.',
  'Développé couché poulies': 'Banc entre deux poulies, pousser en rapprochant les mains, tension constante.',
  'Rowing machine Hammer (unilatéral)': 'Poitrine contre l’appui, tirer le coude vers l’arrière, un bras à la fois.',
  'Tirage vertical machine convergente': 'Amener les coudes vers les hanches, poitrine sortie, sans tirer avec le dos.',
  'Curl machine': 'Coude aligné avec l’axe de la machine, montée complète, descente contrôlée.',
  'Extension triceps machine': 'Coudes fixes sur l’appui, verrouiller l’extension.',
  'Élévations latérales machine': 'Coudes sur les appuis, monter jusqu’à l’horizontale sans hausser les épaules.',
  'Abduction de hanche à la poulie': 'Sangle à la cheville, buste droit, écarter la jambe sans incliner le tronc.',
  'Adduction de hanche à la poulie': 'Sangle à la cheville, ramener la jambe devant l’autre, bassin fixe.',
  'Hip thrust machine': 'Menton rentré, rétroversion du bassin en haut, pause d’une seconde.',
  'Machine à mollets debout': 'Amplitude complète, pause en bas en étirement, genoux tendus.',
  'Crunch machine': 'Enrouler le tronc, ne pas tirer avec les bras.',
  'Rotation du buste machine': 'Bassin bloqué, rotation lente et contrôlée dans les deux sens.',
  'Squat tempo (excentrique 3-5 s)': 'Descente lente et régulière ; charge réduite d’environ 20 %.',
  'Soulevé de terre avec arrêt sous les genoux': 'Marquer 2 s juste sous les genoux, dos neutre, barre contre les jambes.',
  'Développé couché avec planche (board press)': 'Planche de 2 à 4 cm sur la poitrine : surcharge du haut du mouvement.',
  'Développé couché au tempo': 'Par exemple 3 s de descente, 1 s de pause, montée explosive.',
  'Développé militaire assis à la barre': 'Dos contre le dossier, gainé, la tête recule pour laisser passer la barre.',
  'Rowing barre poitrine sur banc': 'Allongé ventre sur un banc haut, tirer la barre vers le banc sans élan.',
  'Hip thrust tempo avec pause': 'Pause de 2 à 3 s en haut, descente lente.',
  'Fentes avant barre': 'Grand pas, genou arrière qui frôle le sol, buste droit.',
  'Squat bulgare barre': 'Barre sur le dos, pied arrière sur le banc, descendre à la verticale.',
  'Good morning assis': 'Assis jambes écartées, pencher le buste dos neutre, remonter en contractant le bas du dos.',
  'Leg curl excentrique unilatéral': 'Monter à deux jambes, redescendre sur une seule en 3 à 5 s.',
  'Soulevé de terre roumain unilatéral léger': 'Charge légère, contrôle de l’équilibre et du bassin avant la charge.',
  'Sauts sur place à cloche-pied (retour au sport)': 'Sauts courts et réguliers sur une jambe, réception silencieuse, genou aligné.',
  'Rotation externe de hanche à l’élastique (assis)': 'Assis au bord d’une chaise, élastique à la cheville, tourner le pied vers l’intérieur (la hanche tourne en externe).',
  'Rotation interne de hanche à l’élastique (assis)': 'Assis, élastique à la cheville, tourner le pied vers l’extérieur (la hanche tourne en interne).',
  'Flexion de hanche à l’élastique debout': 'Élastique à la cheville, monter le genou à 90° sans arrondir le dos.',
  'Dorsiflexion de poignet en appui (préparation handstand)': 'À quatre pattes, mains à plat, pencher progressivement les épaules au-delà des mains.',
  'Extension de doigts sur élastique et prise en pince': 'Ouvrir les doigts contre l’élastique, puis serrer une pince pouce-doigts.',
  'Rotation de poignet au marteau en pronation lente': 'Tourner vers la pronation en 3 s ; plus la main tient loin de la tête, plus c’est dur.',
  'Ouverture de la cage thoracique couché (respiration latérale)': 'Mains sur les côtes, inspirer en écartant les côtes sur les côtés, expiration longue.',
  'Rétraction cervicale avec extension': 'Rentrer le menton puis incliner doucement la tête en arrière, retour menton rentré.',
  'Rotation cervicale active assistée': 'Tourner la tête jusqu’à la limite, aider légèrement avec la main, sans douleur.',
  'Glissement neural du nerf médian': 'Bras tendu sur le côté, étendre le poignet en inclinant la tête du côté opposé, puis relâcher : mouvement de va-et-vient doux.',
  'Assault bike / vélo à air': 'Pousser et tirer avec les bras en même temps que les jambes ; idéal en intervalles.',
  'Battle rope': 'Genoux fléchis, gainé, ondulations rapides depuis les épaules.',
  'Corde à sauter': 'Sauts bas sur l’avant-pied, rotation par les poignets.',
  'Mountain climbers': 'En planche, ramener les genoux alternativement vers la poitrine sans lever les fesses.',
  'Sled drag (traîneau tiré en avançant)': 'Harnais à la taille, pas courts et puissants, buste penché.',
  'Relevé de bord externe du pied (éversion pied nu)': 'Lever le bord externe du pied en gardant le gros orteil au sol.',
  'Ouverture et fermeture de la main (doigts écartés)': 'Écarter les doigts au maximum contre l’élastique, puis les resserrer.',
  'Tractions prise large': 'Mains plus larges que les épaules, tirer la poitrine vers la barre, coudes vers le bas.',
  'Tractions lestées': 'Charge à la ceinture ou gilet, même technique que les tractions strictes.',
  'Tractions assistées élastique': 'Genou ou pied dans l’élastique, diminuer l’aide progressivement.',
  'Traction un bras': 'Main libre sur la poitrine, corps gainé ; travailler d’abord les tractions archer.',
  'Tirage vertical prise serrée': 'Poignée triangle, tirer vers le haut de la poitrine, coudes près du corps.',
  'Tirage vertical unilatéral': 'Laisser monter l’épaule en étirement, puis tirer le coude vers la hanche.',
  'Rowing Yates (prise supination)': 'Buste plus redressé (environ 30°), tirer vers le bas du ventre.',
  'Rowing T-bar': 'Poitrine sortie, tirer la charge vers le bas des pectoraux.',
  'Rowing Meadows': 'Debout de côté à la landmine, tirer l’extrémité de la barre, coude haut et en arrière.',
  'Rowing poitrine sur banc incliné (Seal row)': 'Poitrine contre le banc incliné, tirer sans décoller le buste.',
  'Rowing inversé à la barre': 'Corps gainé en planche, tirer la poitrine vers la barre ; plus les pieds sont hauts, plus c’est dur.',
  'Shrugs barre': 'Barre devant les cuisses, monter les épaules vers les oreilles, pause en haut.',
  'Shrugs trap bar': 'Prise neutre au centre de la barre hexagonale, épaules vers les oreilles.',
  'Rétraction scapulaire à la poulie': 'Bras tendus, rapprocher seulement les omoplates sans plier les coudes.',
  'Superman': 'Allongé ventre, lever bras et jambes en regardant le sol, tenir 2 à 3 s.',
  'Écarté incliné haltères': 'Banc à 30°, coudes légèrement fléchis, ouvrir jusqu’à l’étirement du haut des pecs.',
  'Pompes larges': 'Mains plus larges que les épaules, descendre la poitrine entre les mains.',
  'Pompes pieds surélevés': 'Pieds sur un banc, corps gainé : plus de haut des pectoraux et d’épaules.',
  'Dips lestés': 'Ceinture de lest, descendre jusqu’à l’épaule au niveau du coude, épaules basses.',
  'Développé militaire haltères assis': 'Dossier quasi vertical, haltères à hauteur d’oreilles, pousser sans cambrer.',
  'Développé épaules machine': 'Poignées à hauteur d’épaules, dos plaqué, verrouiller en haut.',
  'Élévations frontales': 'Monter bras tendus jusqu’à hauteur d’yeux, sans élan.',
  'Reverse pec deck': 'Poitrine contre l’appui, ouvrir les bras jusqu’au plan du corps.',
  'Développé couché en rotation externe (L-press)': 'Allongé, coude à 90°, faire tourner l’haltère vers l’arrière en gardant le coude fixe.',
  'Wall walk': 'Depuis la planche, remonter les pieds le long du mur en rapprochant les mains, corps gainé.',
  'Curl pupitre (Larry Scott)': 'Bras posés sur le pupitre, descente complète mais contrôlée.',
  'Curl concentré': 'Assis, coude contre l’intérieur de la cuisse, supiner en haut.',
  'Extension triceps poulie au-dessus de la tête': 'Dos à la poulie, coudes près de la tête, étirer le triceps en bas.',
  'Kickback haltère': 'Buste penché, bras collé au corps, tendre le coude jusqu’au verrouillage.',
  'Dips machine': 'Épaules basses, pousser jusqu’à l’extension complète.',
  'Extension des poignets': 'Avant-bras posés paumes vers le bas, relever la main lentement.',
  'Rouleau à poignets (wrist roller)': 'Bras tendus devant soi, enrouler puis dérouler la corde lentement.',
  'Suspension un bras': 'Épaule active (pas pendue sur les ligaments), changer de bras.',
  'Écrasement de balle (grip)': 'Serrer fort 3 à 5 s, relâcher ; balle souple en réhab.',
  'Squat Smith': 'Pieds légèrement devant la barre, descendre sous la parallèle.',
  'Presse à cuisses unilatérale': 'Genou aligné avec le pied, bassin qui reste collé au dossier.',
  'Pendulum squat': 'Pieds au milieu de la plateforme, descendre le plus bas possible.',
  'Squat au poids du corps': 'Pieds largeur d’épaules, hanches en arrière et en bas, talons au sol.',
  'Pistol squat assisté (box ou sangle)': 'S’asseoir sur une box de plus en plus basse, ou s’aider d’une sangle.',
  'Soulevé de terre jambes tendues': 'Genoux presque tendus, descendre la barre jusqu’à l’étirement des ischios, dos neutre.',
  'Hip thrust unilatéral': 'Une jambe tendue en l’air, bassin qui reste horizontal.',
  'Pont fessier': 'Talons proches des fesses, pousser dans les talons, serrer les fessiers en haut.',
  'Pont fessier une jambe': 'Une jambe tendue, bassin qui ne bascule pas.',
  'Kickback fessier poulie': 'Buste penché, pousser la jambe en arrière sans cambrer.',
  'Glute-ham raise': 'Genoux juste derrière l’appui, remonter en tirant avec les ischios.',
  'Leg curl couché': 'Bassin collé au banc, montée complète, descente contrôlée.',
  'Leg curl debout unilatéral': 'Buste fixe, ramener le talon vers la fesse.',
  'Leg curl au swiss ball': 'Hanches hautes, ramener le ballon vers les fesses avec les talons.',
  'Glissade ischios (slider curl)': 'Pont fessier, glisser les talons loin puis les ramener sans baisser les hanches.',
  'Fentes avant': 'Grand pas, genou avant au-dessus du pied, buste droit.',
  'Fentes marchées': 'Enchaîner les fentes en avançant, sans pause en haut.',
  'Fentes latérales': 'Grand pas de côté, fesses en arrière, l’autre jambe tendue.',
  'Fente croisée (curtsy lunge)': 'Pied arrière qui croise derrière, bassin face à l’avant.',
  'Leg extension': 'Dos plaqué, extension complète, descente lente.',
  'Leg extension unilatéral': 'Une jambe à la fois pour corriger les déséquilibres.',
  'Machine abducteurs': 'Buste droit ou légèrement penché en avant pour cibler les fessiers.',
  'Machine adducteurs': 'Amplitude progressive, pause en fermeture.',
  'Adduction à l’élastique': 'Élastique à la cheville, ramener la jambe vers l’autre, bassin fixe.',
  'Planche latérale avec abduction': 'En planche latérale, lever la jambe du dessus sans baisser les hanches.',
  'Fire hydrant': 'À quatre pattes, lever le genou sur le côté sans tourner le dos.',
  'Extensions mollets à la presse': 'Pointes de pieds au bord de la plateforme, amplitude complète.',
  'Marche sur les talons': 'Pointes de pieds relevées, petits pas.',
  'Marche sur les pointes': 'Talons hauts, genoux tendus, petits pas réguliers.',
  'Inversion de cheville à l’élastique': 'Tourner la plante du pied vers l’intérieur contre l’élastique.',
  'Ramasser une serviette avec les orteils': 'Pied à plat, froisser la serviette avec les orteils.',
  'Rotation interne à l’élastique': 'Coude au corps, serviette sous le coude, ramener la main vers le ventre.',
  'Rotation externe isométrique contre le mur': 'Coude à 90° au corps, pousser le dos de la main contre le mur sans bouger.',
  'Wall slide avec rouleau en mousse': 'Avant-bras sur le rouleau contre le mur, le faire rouler vers le haut en écartant les omoplates.',
  'Pompe sur genoux plus': 'Pompe sur les genoux, puis pousser encore pour écarter les omoplates.',
  'Rowing bas à l’élastique': 'Tirer les coudes vers l’arrière en abaissant les omoplates.',
  'Marche à quatre pattes sur les mains (crawl)': 'Genoux à quelques cm du sol, avancer main et pied opposés.',
  'Mini-squat à 45°': 'Descendre jusqu’à 45° de flexion de genou, genou aligné avec le pied.',
  'Leg press amplitude réduite (0-60°)': 'Limiter la descente à 60° de flexion de genou.',
  'Course arrière': 'Petits pas sur l’avant-pied, buste droit.',
  'Patella mobilisation (auto-mobilisation de la rotule)': 'Jambe tendue relâchée, déplacer la rotule doucement en haut, en bas et sur les côtés.',
  'Pont avec élastique aux genoux': 'Pousser les genoux vers l’extérieur contre l’élastique pendant le pont.',
  'Marche fermier unilatérale lente': 'Charge d’un côté, marcher lentement en restant parfaitement droit.',
  'Pigeon (étirement du fessier)': 'Jambe avant pliée devant soi, jambe arrière tendue, pencher le buste vers l’avant.',
  'Étirement des adducteurs (grenouille)': 'À quatre pattes, genoux écartés, reculer le bassin doucement.',
  'Étirement des pectoraux (encadrement de porte)': 'Avant-bras contre le cadre, coude à hauteur d’épaule, avancer le buste.',
  'Étirement du grand dorsal (prière)': 'À genoux, mains loin devant sur un banc, descendre la poitrine.',
  'Extension thoracique sur rouleau': 'Rouleau sous le haut du dos, mains derrière la tête, s’étendre par-dessus.',
  'Étirement des extenseurs du poignet': 'Bras tendu, paume vers le bas, tirer doucement les doigts vers soi.',
  'Squat profond tenu': 'Talons au sol, coudes poussant les genoux vers l’extérieur, buste droit.',
  'Pancake (écart facial penché)': 'Jambes écartées, pencher le buste depuis les hanches, dos plat.',
  'Auto-massage au rouleau (quadriceps)': 'Rouler lentement, s’arrêter sur les zones tendues 20 à 30 s.',
  'Auto-massage à la balle (fessiers)': 'Assis sur la balle, jambe croisée, rouler doucement sur le fessier.',
  'Planche latérale': 'Coude sous l’épaule, corps aligné, hanches hautes.',
  'Arch body (superman tenu)': 'Allongé ventre, bras et jambes tendus levés, fessiers serrés.',
  'Ab wheel debout': 'Depuis debout, rouler jusqu’au sol sans creuser le dos : niveau très avancé.',
  'Toes to bar': 'Enrouler le bassin pour amener les pieds à la barre, sans balancer.',
  'Relevé de genoux suspendu': 'Monter les genoux à la poitrine en enroulant le bassin.',
  'V-sit / V-up': 'Monter bras et jambes en même temps, toucher les pieds, descendre contrôlé.',
  'Russian twist': 'Buste incliné, pieds au sol ou levés, tourner les épaules d’un côté à l’autre.',
  'Rotation landmine': 'Bras tendus, faire décrire un arc à la barre en pivotant sur les pieds.',
  'Flexion latérale haltère': 'Haltère d’un côté, s’incliner puis remonter avec le côté opposé.',
  'Stir the pot (swiss ball)': 'Avant-bras sur le ballon, dessiner des petits cercles sans bouger le bassin.',
  'Back extension isométrique': 'Tenir l’alignement jambes-buste à l’horizontale sur le banc.',
  'Renforcement cou en flexion (bandeau)': 'Allongé sur le dos, rentrer le menton puis lever la tête contre la charge.',
  'Saut en longueur sans élan': 'Bras en arrière, impulsion des deux pieds, réception amortie.',
  'Sauts groupés': 'Monter les genoux à la poitrine, réception souple, enchaîner.',
  'Bonds unipodaux': 'Sauts vers l’avant sur une jambe, genou aligné à chaque réception.',
  'Skater jumps': 'Bond latéral d’une jambe à l’autre, stabiliser chaque réception.',
  'Lancer de medecine ball rotation': 'De côté au mur, rotation des hanches puis des épaules, lancer explosif.',
  'Lancer de medecine ball au-dessus de la tête (slam)': 'Monter le ballon au-dessus de la tête, l’écraser au sol de tout le corps.',
  'Lancer poitrine de medecine ball': 'Pousser le ballon depuis la poitrine le plus fort possible.',
  'Montées de genoux (A-skip)': 'Genou à hauteur de hanche, pied qui griffe le sol sous le bassin.',
  'Fentes sautées': 'Changer de jambe en l’air, réception en fente contrôlée.',
  'Burpee': 'Poitrine au sol, retour accroupi, saut final bras en l’air.',
  'Arraché (power snatch)': 'Prise large, barre près du corps, extension complète puis réception bras tendus.',
  'Épaulé-jeté (jerk)': 'Flexion-extension des jambes, passer sous la barre bras verrouillés.',
  'Tirage haut (clean pull)': 'Comme l’épaulé sans réception : extension complète et haussement d’épaules.',
  'Arraché haltère un bras': 'Haltère entre les pieds, extension de hanche explosive, bras verrouillé en haut.',
  'Yoke walk': 'Charge haute sur le dos, pas courts et rapides, gainage maximal.',
  'Port de sandbag (bear hug)': 'Sac serré contre la poitrine, marcher droit.',
  'Atlas stone / sandbag au-dessus de l’épaule': 'Ramasser le sac entre les jambes, l’amener aux hanches, extension explosive pour le passer au-dessus de l’épaule.',
  'Retournement de pneu': 'Poitrine contre le pneu, pousser avec les jambes, puis basculer avec les bras.',
  'Rack carry (front rack)': 'Kettlebells en rack, coudes serrés, marcher droit sans cambrer.',
};
